### ISSUE TITLE
IndexError in _get_tool_calls: Handling empty 'choices' list in message data

### ISSUE THREAD

**Issue by haven-jeon** [poe-platform/fastapi_poe#122]
## Description

An IndexError is occurring in the `_get_tool_calls` function when attempting to access the `finish_reason` of the first choice in the `message.data["choices"]` list. This error suggests that the list is empty when the code attempts to access its first element.

## Error Message

```
ERROR: Error responding to query
Traceback (most recent call last):
  File "/home/gogamza/miniconda3/envs/godotbot/lib/python3.12/site-packages/fastapi_poe/base.py", line 705, in handle_query
    async for event in self.get_response_with_context(request, context):
  File "/home/gogamza/miniconda3/envs/godotbot/lib/python3.12/site-packages/fastapi_poe/base.py", line 184, in get_response_with_context
    async for event in self.get_response(request):
  File "/home/gogamza/work/godot-engine/src/godot_rag_fastapi_v2.py", line 238, in get_response
    async for msg in fp.stream_request(
  File "/home/gogamza/miniconda3/envs/godotbot/lib/python3.12/site-packages/fastapi_poe/client.py", line 334, in stream_request
    tool_calls = await _get_tool_calls(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gogamza/miniconda3/envs/godotbot/lib/python3.12/site-packages/fastapi_poe/client.py", line 431, in _get_tool_calls
    finish_reason = message.data["choices"][0]["finish_reason"]
                    ~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

## Current Behavior

The function attempts to access the first element of `message.data["choices"]` without first checking if the list is empty, leading to an IndexError when the list is empty.

## Expected Behavior

The function should handle cases where `message.data["choices"]` is an empty list, either by skipping such messages or by providing a default value for `finish_reason`.

## Possible Solution

Update the `_get_tool_calls` function to include a check for empty choices before attempting to access the first element. For example:

```python
if not isinstance(message.data, dict) or not message.data.get("choices"):
    print("Received invalid message data or empty choices")
    continue
finish_reason = message.data["choices"][0].get("finish_reason")
```

## Additional Context

This error is occurring in the context of a FastAPI application using the `fastapi_poe` library. The error happens during the streaming of responses, specifically in the `_get_tool_calls` function.

## Environment

- Python version: 3.12
- fastapi_poe version: 0.0.48
- Operating System: ubuntu

**Comment by JohntheLi** [comment]
Thanks for the report. This issue should be fixed in v0.0.53!
