### ISSUE TITLE
Using the code, i get the error 

### ISSUE THREAD

**Issue by Drak0** [poe-platform/fastapi_poe#8]
i followed the tutorial in here : https://developer.poe.com/api-bots/quick-start
i also enabled the POE_API_KEY, i send it in the request in the BEARER.

EchoBot and HuggingFaceBot works perfectly when making an api calling using postman.
however, when switching to ChatGPTAllCapsBot or the example in here https://developer.poe.com/api-bots/api-to-access-bots-on-poe i get the error below:

```
Sending request to chatGPT...
Request finished with status 200. (execution time: 6.9 ms, total latency: 1805.2 ms)
Error in Poe API Bot: Bot request to chatGPT failed on try 0 {"allow_retry": true, "text": "Internal server error"}
Error in Poe API Bot: Bot request to chatGPT failed on try 1 {"allow_retry": true, "text": "Internal server error"}
Error occurred: Error communicating with bot chatGPT
Error responding to query
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fastapi_poe/client.py", line 321, in stream_request
    async for message in ctx.perform_query_request(request):
  File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1580, in stream
    yield response
  File "/usr/local/lib/python3.11/site-packages/httpx_sse/_api.py", line 70, in aconnect_sse
    yield EventSource(response)
  File "/usr/local/lib/python3.11/site-packages/fastapi_poe/client.py", line 225, in perform_query_request
    raise BotError(event.data)
fastapi_poe.client.BotError: {"allow_retry": true, "text": "Internal server error"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fastapi_poe/base.py", line 169, in handle_query
    async for event in self.get_response(query):
  File "/root/chatgpt_allcapsbot.py", line 33, in get_response
    raise e
  File "/root/chatgpt_allcapsbot.py", line 12, in get_response
    async for msg in stream_request(query, "chatGPT", query.api_key):
  File "/usr/local/lib/python3.11/site-packages/fastapi_poe/client.py", line 330, in stream_request
    raise BotError(f"Error communicating with bot {bot_name}") from e
fastapi_poe.client.BotError: Error communicating with bot chatGPT
```

if i use the BOT i created by sending aprompt from the POE website, it works.

**Comment by JelleZijlstra** [comment]
I see some internal errors that might correspond to your requests. I'll push a change so we output something better than "Internal server error" in that case.

**Comment by Drak0** [comment]
I am so sorry, this belongs to the API Bot Tutorial, i will open it in there.
However, can i use ur fastapi implementation for making API calls to the bots in my poe.com account?

thank you

**Comment by JelleZijlstra** [comment]
The current API only allows bots to be accessed through the Poe clients (web, ios, and android). Those bots can then access other bots (through `fastapi_poe.client`) to help power their responses.
